platform :ios, '8.0'
#use_frameworks!

target 'ChartDemo' do
  pod 'CorePlot', '~> 2.1'
  pod 'PNChart', '~> 0.8.5'
  pod 'CJFMDBFileManager', '~> 1.1.0'
  pod 'CommonInfoHelper', '~> 0.0.2'
  
  pod 'CJPopupAction', '~> 1.4.2'
  pod 'CJPickerToolBarView', '~> 0.0.3'
  
  pod 'CJCategory', '~> 0.0.4'
  
end

target 'ChartDemoTests' do
   
end
